---

- name: Cloning {{drdc_name}} service container
  git:
    repo: '{{drdc_repo}}'
    version: HEAD
    force: yes
    accept_hostkey: yes
    dest: '{{drdc_dir}}'
  when: 'drdc_repo is defined'
#    ssh_opts: ' -o StrictHostKeyChecking=no'


- name: Building {{drdc_name}} service image
  docker_image:
    force: yes
    path: '{{drdc_dir|default(drdc_name)}}'
    name: '{{drdc_image}}'

- name: Creating {{drdc_name}} service container
  docker_container:
    name: '{{drdc_name}}'
    hostname: '{{drdc_name}}'
    recreate: '{{drdc_recreate}}'
    state: started
    pull: '{{drdc_pull}}'
    restart: yes
    restart_policy: '{{drdc_restart_policy}}'
    memory: '{{drdc_memory_limit}}'
    image: '{{drdc_image}}'
    volumes: '{{drdc_volumes}}'
    purge_networks: yes
    networks: '{{drdc_networks}}'
    ports: '{{drdc_ports}}'
    env: '{{drdc_env}}'
    command: '{{drdc_cmd|default(omit)}}'
