---

- name: Cloning {{drdc_name}} service
  git:
    repo: '{{drdc_repo}}'
    version: HEAD
    force: yes
    accept_hostkey: yes
    dest: '{{drdc_dir|default(drdc_name)}}'
#    ssh_opts: ' -o StrictHostKeyChecking=no'


- name: Building {{drdc_name}} service image
  docker_image:
    force: yes
    path: '{{drdc_dir|default(drdc_name)}}'
    name: '{{drdc_image}}'

- name: Creating {{drdc_name}} serrvice container
  docker_container:
    name: '{{drdc_name}}'
    hostname: '{{drdc_name}}'
    recreate: yes
    state: started
    restart: yes
    restart_policy: always
    image: '{{drdc_image}}'
    volumes: '{{drdc_volumes}}'
    purge_networks: yes
    networks: [{name: '{{drdc_network}}'}]
    ports: '{{drdc_ports}}'
    env: '{{drdc_env}}'
